MVC/04-asp.net-mvc/module 05 - Developing ASP.NET MVC Views/Lab/Solution/PhotoSharingApplication/PhotoSharingApplication/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhotoSharingApplication.Models
{
    public class Photo
    {
        //PhotoID. This is the primary key
        public int PhotoID { get; set; }

        //Title. The title of the photo
        [Required]
        public string Title { get; set; }

        //PhotoFile. This is a picture file
        [DisplayName("Picture")]
        [MaxLength]
        public byte[] PhotoFile { get; set; }

        //ImageMimeType, stores the MIME type for the PhotoFile
        [HiddenInput(DisplayValue = false)]
        public string ImageMimeType { get; set; }

        //Description.
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        //CreatedDate
        [DataType(DataType.DateTime)]
        [DisplayName("Created Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yy}", ApplyFormatInEditMode = true)]
        public DateTime CreatedDate { get; set; }

        //UserName. This is the name of the user who created the photo
        public string UserName { get; set; }

        //All the comments on this photo, as a navigation property
        public virtual ICollection<Comment> Comments { get; set; }

    }
}

MVC/04-asp.net-mvc/module 05 - Developing ASP.NET MVC Views/Lab/Solution/PhotoSharingApplication/PhotoSharingApplication/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;
using System.Globalization;
using PhotoSharingApplication.Models;

namespace PhotoSharingApplication.Controllers
{
    [ValueReporter]
    public class PhotoController : Controller
    {
        private PhotoSharingContext context = new PhotoSharingContext();

        //
        // GET: /Photo/

        public ActionResult Index()
        {
            return View("Index");
        }

        [ChildActionOnly]
        public ActionResult _PhotoGallery(int number = 0)
        {
            List<Photo> photos;

            if (number == 0)
            {
                photos = context.Photos.ToList();
            }
            else
            {
                photos = (from p in context.Photos
                          orderby p.CreatedDate descending
                          select p).Take(number).ToList();
            }

            return PartialView("_PhotoGallery", photos);
        }

        public ActionResult Display(int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Display", photo);
        }

        public ActionResult Create()
        {
            Photo newPhoto = new Photo();
            newPhoto.CreatedDate = DateTime.Today;
            return View("Create", newPhoto);
        }

        [HttpPost]
        public ActionResult Create(Photo photo, HttpPostedFileBase image)
        {
            photo.CreatedDate = DateTime.Today;
            if (!ModelState.IsValid)
            {
                return View("Create", photo);
            }
            else
            {
                if (image != null)
                {
                    photo.ImageMimeType = image.ContentType;
                    photo.PhotoFile = new byte[image.ContentLength];
                    image.InputStream.Read(photo.PhotoFile, 0, image.ContentLength);
                }
                context.Photos.Add(photo);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Delete", photo);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = context.Photos.Find(id);
            context.Photos.Remove(photo);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public FileContentResult GetImage(int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo != null)
            {
                return File(photo.PhotoFile, photo.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

MVC/04-asp.net-mvc/module 05 - Developing ASP.NET MVC Views/Lab/Solution/PhotoSharingApplication/PhotoSharingApplication/Views/Photo/Create.cshtml
@model PhotoSharingApplication.Models.Photo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create New Photo</title>
</head>
<body>
    <div>
        <h2>Create New Photo</h2>

        @using (Html.BeginForm("Create", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(true)

            <p>
                @Html.LabelFor(model => model.Title):
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </p>
            
            <p>
                @Html.LabelFor(model => model.PhotoFile)
                <input type="file" name="Image" />
            </p>
            
            <p>
                @Html.LabelFor(model => model.Description):
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </p>
            
            <p>
                @Html.LabelFor(model => model.UserName):
                @Html.DisplayFor(model => model.UserName)
            </p>

            <p>
                @Html.LabelFor(model => model.CreatedDate):
                @Html.DisplayFor(model => model.CreatedDate)
            </p>
            
            <p>
                <input type="submit" value="Create" />
                @Html.ActionLink("Back to List", "Index")
            </p>
        }
    </div>
</body>
</html>

MVC/04-asp.net-mvc/module 05 - Developing ASP.NET MVC Views/Lab/Solution/PhotoSharingApplication/PhotoSharingApplication/Views/Photo/Display.cshtml
@model PhotoSharingApplication.Models.Photo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Model.Title</title>
</head>
<body>
    <div>
        <h2>"@Model.Title"</h2>

        <img width="800" src="@Url.Action("GetImage", "Photo", new { id = Model.PhotoID })" />

        <p>
            @Html.DisplayFor(model => model.Description)
        </p>

        <p>
            @Html.DisplayNameFor(model => model.UserName):
            @Html.DisplayFor(model => model.UserName)
        </p>

        <p>
            @Html.DisplayNameFor(model => model.CreatedDate):
            @Html.DisplayFor(model => model.CreatedDate)
        </p>

        <p>
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</body>
</html>

MVC/04-asp.net-mvc/module 05 - Developing ASP.NET MVC Views/Lab/Solution/PhotoSharingApplication/PhotoSharingApplication/Views/Photo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>All Photos</title>
</head>
<body>
    <div>
        <h2>All Photos</h2>

        <p>
            @Html.ActionLink("Add a Photo", "Create", "Photo")
        </p>

        @Html.Action("_PhotoGallery", "Photo")
    </div>
</body>
</html>