MVC/04-asp.net-mvc/module 07 - Structuring ASP.NET MVC Web Applications/Demo/OperasWebSite/OperasWebSite/Models/Opera.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OperasWebSite.Models
{
    public class Opera
    {
        public int OperaID { get; set; }
        [Required]
        [StringLength(200)]
        public string Title { get; set; }
        [CheckValidYear]
        public int Year { get; set; }
        [Required]
        public string Composer { get; set; }
    }

    public class CheckValidYear : ValidationAttribute
    {
        public CheckValidYear()
        {
            ErrorMessage = "The earliest opera is Daphne, 1598, by Corsi, Peri, and Rinuccini";
        }

        public override bool IsValid(object value)
        {
            int year = (int)value;
            if (year < 1598)
            {
                return false;
            }
            else
            {
                return true;
            }
        }
    }
}

MVC/04-asp.net-mvc/module 07 - Structuring ASP.NET MVC Web Applications/Demo/OperasWebSite/OperasWebSite/Models/OperasDB.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace OperasWebSite.Models
{
    public class OperasDB : DbContext
    {
        public DbSet<Opera> Operas { get; set; }
    }
}

MVC/04-asp.net-mvc/module 07 - Structuring ASP.NET MVC Web Applications/Demo/OperasWebSite/OperasWebSite/Models/OperasInitializer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace OperasWebSite.Models
{
    public class OperasInitializer : DropCreateDatabaseAlways<OperasDB>
    {
        protected override void Seed(OperasDB context)
        {
            base.Seed(context);

            var operas = new List<Opera>
            {
                new Opera {
                    Title = "Cosi Fan Tutte",
                    Year = 1790,
                    Composer = "Wolfgang Amadeus Mozart",
                },
                new Opera {
                    Title = "Rigoletto",
                    Year = 1851,
                    Composer = "Giuseppe Verdi",
                },
                new Opera {
                    Title = "Nixon in China",
                    Year = 1987,
                    Composer = "John Adams"
                },
                new Opera {
                    Title = "Wozzeck",
                    Year = 1922,
                    Composer = "Alban Berg"
                }
            };

            operas.ForEach(s => context.Operas.Add(s));
            context.SaveChanges();
        }
    }
}

MVC/04-asp.net-mvc/module 07 - Structuring ASP.NET MVC Web Applications/Demo/OperasWebSite/OperasWebSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OperasWebSite.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View("Index");
        }

        public ActionResult About()
        {
            return View("");
        }

    }
}

MVC/04-asp.net-mvc/module 07 - Structuring ASP.NET MVC Web Applications/Demo/OperasWebSite/OperasWebSite/Controllers/OperaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using OperasWebSite.Models;

namespace OperasWebSite.Controllers
{
    public class OperaController : Controller
    {
        private OperasDB contextDB = new OperasDB();

        //
        // GET: /Opera/

        public ActionResult Index()
        {
            return View("Index", contextDB.Operas.ToList());
        }

        public ActionResult Details(int id)
        {
            Opera opera = contextDB.Operas.Find(id);
            if (opera != null)
            {
                return View("Details", opera);
            }
            else
            {
                return HttpNotFound();
            }
        }

        public ActionResult Create()
        {
            Opera newOpera = new Opera();
            return View("Create", newOpera);
        }

        [HttpPost]
        public ActionResult Create(Opera newOpera)
        {
            if (ModelState.IsValid)
            {
                contextDB.Operas.Add(newOpera);
                contextDB.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View("Create", newOpera);
            }
        }
    }
}

MVC/04-asp.net-mvc/module 07 - Structuring ASP.NET MVC Web Applications/Demo/OperasWebSite/OperasWebSite/Views/Opera/Create.cshtml
@model OperasWebSite.Models.Opera

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <div>
        <h2>Add an Opera</h2>

        @using (Html.BeginForm("Create", "Opera", FormMethod.Post))
        {
            <p>
                @Html.LabelFor(model => model.Title):
                @Html.EditorFor(model  => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </p>
            
            <p>
                @Html.LabelFor(model => model.Year):
                @Html.EditorFor(model => model.Year)
                @Html.ValidationMessageFor(model => model.Year)
            </p>
            
            <p>
                @Html.LabelFor(model => model.Composer):
                @Html.EditorFor(model => model.Composer)
                @Html.ValidationMessageFor(model => model.Composer)
            </p>
            
            <input type="submit" value="Create" />
            @Html.ActionLink("Back to List", "Index")
        }
    </div>
</body>
</html>

MVC/04-asp.net-mvc/module 07 - Structuring ASP.NET MVC Web Applications/Demo/OperasWebSite/OperasWebSite/Views/Opera/Details.cshtml
@model OperasWebSite.Models.Opera

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    
    
    <h2>
        @Html.DisplayFor(model => model.Title)
    </h2>
   
    <div> 
        <span class="display-label">
                @Html.DisplayNameFor(model => model.Year):
        </span>
        <span class="display-field">
            @Html.DisplayFor(model => model.Year)
        </span>
    </div>

    <div>
        <span class="display-label">
                @Html.DisplayNameFor(model => model.Composer):
        </span>
        <span class="display-field">
            @Html.DisplayFor(model => model.Composer)
        </span>
    </div>
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

MVC/04-asp.net-mvc/module 07 - Structuring ASP.NET MVC Web Applications/Demo/OperasWebSite/OperasWebSite/Views/Opera/Index.cshtml
@model IEnumerable<OperasWebSite.Models.Opera>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>
        Main Opera List
    </h2>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table style="width: 600px;">
        <tr style="background-color: lightgrey;">
            <th style="width: 200px;">
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th style="width: 100px;">
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th style="width: 300px;">
                @Html.DisplayNameFor(model => model.Composer)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Composer)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.OperaID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>