MVC/04-asp.net-mvc/module 01 - Exploring ASP.NET MVC/Demo/PhotoSharingSample/PhotoSharingSample/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhotoSharingApplication.Models;

namespace PhotoSharingApplication.Controllers
{

    public class CommentController : Controller
    {
        private PhotoSharingDB db = new PhotoSharingDB();

        //
        // GET: A Partial View for displaying in the Photo Details view
        [ChildActionOnly] //This attribute means the action cannot be accessed from the brower's address bar
        public PartialViewResult _CommentsForPhoto(int PhotoId)
        {
            //The comments for a particular photo have been requested. Get those comments.
            var comments = from c in db.Comments
                           where c.PhotoID == PhotoId
                           select c;
            //Save the PhotoID in the ViewBag because we'll need it in the view
            ViewBag.PhotoId = PhotoId;
            return PartialView(comments.ToList());
        }

        //
        //POST: This action creates the comment when the AJAX comment create tool is used
        [HttpPost]
        public PartialViewResult _CommentsForPhoto(Comment comment, int PhotoId)
        {
            //The comment comes from the currently authenticated user
            comment.UserName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name);

            //Save the new comment
            db.Comments.Add(comment);
            db.SaveChanges();

            //Get the updated list of comments
            var comments = from c in db.Comments
                            where c.PhotoID == PhotoId
                            select c;
            //Save the PhotoID in the ViewBag because we'll need it in the view
            ViewBag.PhotoId = PhotoId;
            //Return the view with the new list of comments
            return PartialView("_CommentsForPhoto", comments.ToList());
        }

        //
        // GET: /Comment/CreateInline. A Partial View for displaying the create comment tool as a AJAX partial page update
        [Authorize]
        public PartialViewResult _Create(int PhotoId)
        {
            //Create the new comment
            Comment newComment = new Comment();
            newComment.PhotoID = PhotoId;
            newComment.UserName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name);

            ViewBag.PhotoID = PhotoId;
            return PartialView("_AddAComment");
        }

        //
        // GET: /Comment/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            ViewBag.PhotoID = comment.PhotoID;
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Details", "Photo", new { id = comment.PhotoID });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MVC/04-asp.net-mvc/module 01 - Exploring ASP.NET MVC/Demo/PhotoSharingSample/PhotoSharingSample/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhotoSharingApplication.Models;
using System.Drawing;


namespace PhotoSharingApplication.Controllers
{
    public class PhotoController : Controller
    {
        private PhotoSharingDB db = new PhotoSharingDB();

        //
        // GET: /Photo/
        public ActionResult Index()
        {
            return View("Index", db.Photos.ToList());
        }

        //
        // GET: A Partial View for displaying many photos as cards
        [ChildActionOnly] //This attribute means the action cannot be accessed from the brower's address bar
        public ActionResult _PhotoGallery(int number = 0)
        {
            //We want to display only the latest photos when a positive integer is supplied to the view.
            //Otherwise we'll display them all
            List<Photo> photos;

            if (number == 0)
            {
                photos = db.Photos.ToList();
            }
            else
            {
                 photos = (from p in db.Photos
                          orderby p.CreatedDate descending
                          select p).Take(number).ToList();
            }

            return PartialView("_PhotoGallery", photos);
        }

        //
        // GET: This action shows a jQuery-powered slide show that shows all pics in the application
        public ActionResult SlideShow()
        {
            return View(db.Photos.ToList());
        }

        //
        // GET: This actions show the same slideshow view with only the users favorate photos
        public ActionResult FavoritesSlideshow()
        {
            //List<Photo> allPhotos = db.Photos.ToList();
            List<Photo> favPhotos = new List<Photo>();
            List<int> favoriteIds = Session["Favorites"] as List<int>;
            Photo currentPhoto;

            foreach (int favID in favoriteIds)
            {
                currentPhoto = db.Photos.Find(favID);
                if (currentPhoto != null)
                {
                    favPhotos.Add(currentPhoto);
                }
            }

            return View("SlideShow", favPhotos);
        }

        //
        // GET: /Photo/5
        // GET: /Photo/Details/5
        public ActionResult Details(int id = 0)
        {
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Details", photo);
        }

        //
        // GET: /Photo/IncompleteAction 
        //This action is to illustrate exception handling
        public ActionResult IncompleteAction()
        {
            throw new NotImplementedException("This Action is not yet complete");
        }

        //
        // GET: /Photo/Create
        [Authorize]
        public ActionResult Create()
        {
            //Create the new photo
            Photo newPhoto = new Photo();
            newPhoto.UserName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name);
            newPhoto.CreatedDate = DateTime.Today;
            newPhoto.ModifiedDate = DateTime.Today;
            return View(newPhoto);
        }

        //
        // POST: /Photo/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Photo photo, HttpPostedFileBase image)
        {
            photo.UserName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name);
            photo.CreatedDate = DateTime.Today;
            photo.ModifiedDate = DateTime.Today;
            if (ModelState.IsValid)
            {
                //Is there a photo? If so save it
                if (image != null)
                {
                    photo.ImageMimeType = image.ContentType;
                    photo.PhotoFile = new byte[image.ContentLength];
                    image.InputStream.Read(photo.PhotoFile, 0, image.ContentLength);
                }

                //Add the photo to the database and save it
                db.Photos.Add(photo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(photo);
        }

        //
        // GET: /Photo/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        //
        // POST: /Photo/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photos.Find(id);
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //This action gets the photo file for a given Photo ID
        public FileContentResult GetImage(int PhotoId)
        {
            //Get the right photo
            Photo requestedPhoto = db.Photos.FirstOrDefault(p => p.PhotoID == PhotoId);
            if (requestedPhoto != null)
            {
                return File(requestedPhoto.PhotoFile, requestedPhoto.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        //This action adds a photo ID to the list of favorites for the current session
        public ContentResult AddFavorite(int PhotoID)
        {
            List<int> favorites = Session["Favorites"] as List<int>;
            if (favorites == null)
            {
                favorites = new List<int>();
            }
            favorites.Add(PhotoID);
            Session["Favorites"] = favorites;
            return Content("The picture has been added to your favorites", "text/plain", System.Text.Encoding.Default);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MVC/04-asp.net-mvc/module 01 - Exploring ASP.NET MVC/Demo/PhotoSharingSample/PhotoSharingSample/Views/Shared/_AddAComment.cshtml
@model PhotoSharingApplication.Models.Comment

@Html.ValidationSummary(true)

<div class="add-comment-tool">

    <div>
        <span class="comment-editor-label">
            @Html.LabelFor(model => model.Subject)
        </span>
        <span class="comment-editor-field">
            @Html.EditorFor(model => model.Subject)
            @Html.ValidationMessageFor(model => model.Subject)
        </span>
    </div>

    <div>
        <span class="comment-editor-label">
            @Html.LabelFor(model => model.Body)
        </span>
        <span class="comment-editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </span>
    </div>

    <p>
        <input type="submit" value="Create" />
    </p>

</div>

MVC/04-asp.net-mvc/module 01 - Exploring ASP.NET MVC/Demo/PhotoSharingSample/PhotoSharingSample/Views/Shared/_CommentsForPhoto.cshtml
@model IEnumerable<PhotoSharingApplication.Models.Comment>

@{
    AjaxOptions ajaxOptions = new AjaxOptions { UpdateTargetId = "comments-tool" };
}

<h3>Comments</h3>

@using (Ajax.BeginForm("_CommentsForPhoto", new { PhotoId = ViewBag.PhotoId }, ajaxOptions))
{

<div id="comments-tool">
    <div id="all-comments">
    @foreach (var item in Model)
    {
        <div class="photo-comment">

            <div class="photo-comment-from">
                From:
                @Html.DisplayFor(modelItem => item.UserName)
            </div>

            <div class="photo-comment-subject">
                @Html.DisplayNameFor(model => model.Subject):
                @Html.DisplayFor(modelItem => item.Subject)
            </div>

            <div class="photo-comment-body">
                @Html.DisplayFor(modelItem => item.Body)
            </div>

            @Html.ActionLink("Delete This Comment", "Delete", new { id = item.CommentID })

        </div>
    }
    </div>

    <div id="addcomment" class="add-comment-box">
        @if (Request.IsAuthenticated)
        {            
            @Html.Action("_Create", "Comment", new { PhotoID = ViewBag.PhotoId })
        }
        else
        {
            @Html.ActionLink("To comment you must log in", "Login", "Account")
        }
    </div>
</div>
}

MVC/04-asp.net-mvc/module 01 - Exploring ASP.NET MVC/Demo/PhotoSharingSample/PhotoSharingSample/Views/Shared/_MainLayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link type="text/css" rel="stylesheet" href="~/Content/PhotoSharingStyles.css" />
    <script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.8.0.min.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
</head>
<body>

    <h1 class="site-page-title">Photos Unlimited</h1>
    <div class="login-controls">
        @if (Request.IsAuthenticated) {
            <div>
                Hello, @System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name).
                @Html.ActionLink("Log Off", "LogOff", "Account")
                @Html.ActionLink("Reset Password", "ResetPassword", "Account")
            </div>
        } else {
            <div>
                @Html.ActionLink("Log In", "Login", "Account")
                @Html.ActionLink("Register", "Register", "Account")
            </div>
        }
    </div>
    <div class="clear-floats"></div>

    <div id="topmenu">
        <div class="topmenulink">@Html.ActionLink("Home Page", "Index", "Home")</div>
        <div class="topmenulink">@Html.ActionLink("All Photos", "Index", "Photo")</div>
        @if (Request.IsAuthenticated) {
            <div class="topmenulink">@Html.ActionLink("Add a Photo", "Create", "Photo")</div>
        }
        <div class="topmenulink">@Html.ActionLink("Slideshow", "SlideShow", "Photo")</div>
        @if (Session["Favorites"] != null) {
            <div class="topmenulink">@Html.ActionLink("Favorites", "FavoritesSlideshow", "Photo")</div>
        }
    </div>
    
    <div id="page-content">
        @RenderBody()
    </div>

    @RenderSection("Scripts", false)
</body>
</html>

MVC/04-asp.net-mvc/module 01 - Exploring ASP.NET MVC/Demo/PhotoSharingSample/PhotoSharingSample/Views/Shared/_PhotoGallery.cshtml
@model IEnumerable<PhotoSharingApplication.Models.Photo>

@foreach (var item in Model) {

<div class="photo-index-card">

    <h3>
        "@Html.DisplayFor(modelItem => item.Title)"
    </h3>
        
    @if (item.PhotoFile != null) {
        <div class="photo-display">
            <img class="photo-display-img" src="@Url.Action("GetImage", "Photo", new { PhotoId = item.PhotoID })" />
        </div>
    }

    <div class="photo-metadata">
        <div>
            <span class="display-label">
                Created By:
            </span>
            <span class="display-field">
                @Html.DisplayFor(model => item.UserName)
            </span>
        </div>

        <div>
            <span class="display-label">
                    @Html.DisplayNameFor(model => model.CreatedDate):
            </span>
            <span class="display-field">
                @Html.DisplayFor(model => item.CreatedDate)
            </span>
        </div>

        <div>
            <span class="display-label">
                    @Html.DisplayNameFor(model => model.ModifiedDate):
            </span>
            <span class="display-field">
                @Html.DisplayFor(model => item.ModifiedDate)
            </span>
        </div>
    </div>

    @Html.ActionLink("Details", "Details", new { id=item.PhotoID }) |
    @Html.ActionLink("Delete", "Delete", new { id=item.PhotoID })
</div>
}